# Generated by Django 5.0 on 2024-11-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omdata',
            name='MostExpensive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='omdata',
            name='Percentile28',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='omdata',
            name='Price_OM_Target1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='omdata',
            name='Price_SS_Target1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
