# Generated by Django 5.0 on 2024-11-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0003_alter_omdata_accounting_trouble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omdata',
            name='Private_Equity_Model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
