# Generated by Django 5.0 on 2024-11-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0004_alter_omdata_private_equity_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omdata',
            name='MostExpensive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
