# Generated by Django 5.0 on 2024-11-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0007_alter_omdata_beta_alter_omdata_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omdata',
            name='LandSlide_Risk',
        ),
        migrations.RemoveField(
            model_name='omdata',
            name='MostExpensive',
        ),
        migrations.AddField(
            model_name='omdata',
            name='Expensive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='omdata',
            name='LandSlide_RisMostk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
