# Generated by Django 5.0 on 2024-11-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0008_remove_omdata_landslide_risk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omdata',
            old_name='LandSlide_RisMostk',
            new_name='LandSlide_Risk',
        ),
    ]
