# Generated by Django 5.0 on 2024-11-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0009_rename_landslide_rismostk_omdata_landslide_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omdata',
            old_name='Expensive',
            new_name='Most_Expensive',
        ),
    ]
